services:
    django:
        build:
            context: ../..
            dockerfile: deploy/prod/Dockerfile
        command: gunicorn algopath.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/var/www/algopath/static
            - media_volume:/var/www/algopath/media
        expose:
            - 8000
        env_file:
            - ../../envs/.env.prod
    nginx:
        build: nginx
        volumes:
            - static_volume:/var/www/algopath/static
            - media_volume:/var/www/algopath/media
        ports:
            - 8000:80
        depends_on:
            - django

volumes:
    static_volume:
    media_volume: