services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: algopath
      POSTGRES_PASSWORD: algopath
      POSTGRES_DB: algopath
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: